export const CREATE_GAME = 'CREATE_GAME';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';

export const ROTATE_REMAINING_PATHCARD_CLOCKWISE = 'ROTATE_REMAINING_PATHCARD_CLOCKWISE';
export const ROTATE_REMAINING_PATHCARD_CLOCKWISE_OPTIMISTIC = 'ROTATE_REMAINING_PATHCARD_CLOCKWISE_OPTIMISTIC';
