export const CREATE_GAME = 'CREATE_GAME';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';

export const ROTATE_REMAINING_PATHCARD_CLOCKWISE = 'ROTATE_REMAINING_PATHCARD_CLOCKWISE';
export const ROTATE_REMAINING_PATHCARD_CLOCKWISE_OPTIMISTIC = 'ROTATE_REMAINING_PATHCARD_CLOCKWISE_OPTIMISTIC';

export const INSERT_REMAINING_PATHCARD = 'INSERT_REMAINING_PATHCARD';
export const INSERT_REMAINING_PATHCARD_OPTIMISTIC = 'INSERT_REMAINING_PATHCARD_OPTIMISTIC';

export const MOVE_CURRENT_PLAYER_TO = 'MOVE_CURRENT_PLAYER_TO';
export const MOVE_CURRENT_PLAYER_TO_OPTIMISTIC = 'MOVE_CURRENT_PLAYER_TO_OPTIMISTIC';
